apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-sample-app
  name: k8s-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-sample-app
  template:
    metadata:
      labels:
        app: k8s-sample-app
    spec:
      containers:
      - image: k8s-sample-app:1
        imagePullPolicy: IfNotPresent
        name: k8s-sample-app
        ports:
        - name: web
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-sample-app
  labels:
    app: k8s-sample-app
spec:
  ports:
  - name: web
    port: 80
    targetPort: 8080
  selector:
    app: k8s-sample-app
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: k8s-sample-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-sample-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Object
      object:
        target:
          kind: Service
          name: k8s-sample-app
        metricName: replicas
        targetValue: 2